"""empty message

Revision ID: 1dff6dd585b
Revises: None
Create Date: 2015-08-07 12:09:25.091833

"""

# revision identifiers, used by Alembic.
revision = '1dff6dd585b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_name', sa.Integer(), nullable=False),
    sa.Column('setting_value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_settings')
    ### end Alembic commands ###
