"""empty message

Revision ID: 4b1ec8a5b15
Revises: 54435077e60
Create Date: 2015-08-08 08:22:57.730651

"""

# revision identifiers, used by Alembic.
revision = '4b1ec8a5b15'
down_revision = '54435077e60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_settings', sa.Column('collaboration_tool', sa.String(length=100), nullable=False))
    op.drop_column('report_settings', 'collaboration_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_settings', sa.Column('collaboration_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('report_settings', 'collaboration_tool')
    ### end Alembic commands ###
