"""empty message

Revision ID: 87c01509f7
Revises: 4b1ec8a5b15
Create Date: 2015-08-08 08:37:27.068130

"""

# revision identifiers, used by Alembic.
revision = '87c01509f7'
down_revision = '4b1ec8a5b15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
